use p3_koala_bear::KoalaBear;
use serde::{Deserialize, Serialize};
use strum_macros::{EnumDiscriminants, EnumTryAs};
use zkm_core_executor::ZKMReduceProof;
use zkm_hypercube::{config::ZkmGlobalContext, verifier::ZkmPcsProofInner, MachineVerifyingKey, ShardProof, DIGEST_SIZE};
use zkm_primitives::poseidon2_hash;

/// The PCS opening proof type for the core machine (`MipsAir`), used by [`ZKMProof::Core`].
pub type CorePcsProof = ZkmPcsProofInner;

/// A proof generated with Ziren of a particular proof mode.
/// Redefined due to SDK's non-no_std limitation, and is used only for deserialization.
#[derive(Clone, Serialize, Deserialize, EnumDiscriminants, EnumTryAs)]
#[strum_discriminants(derive(Default, Hash, PartialOrd, Ord))]
#[strum_discriminants(name(ZKMProofKind))]
pub enum ZKMProof {
    /// A proof generated by the core proof mode.
    ///
    /// The proof size scales linearly with the number of cycles.
    #[strum_discriminants(default)]
    Core(Vec<ShardProof<ZkmGlobalContext, CorePcsProof>>),
    /// A proof generated by the compress proof mode.
    ///
    /// The proof size is constant, regardless of the number of cycles.
    Compressed(Box<ZKMReduceProof<ZkmGlobalContext, ZkmPcsProofInner>>),
    /// A proof generated by the Plonk proof mode.
    Plonk(PlonkBn254Proof),
    /// A proof generated by the Groth16 proof mode.
    Groth16(Groth16Bn254Proof),
    /// Compressed-proof-to-Groth16 conversion.
    CompressToGroth16,
}

/// A zero-knowledge proof generated by the PLONK protocol with a Base64 encoded gnark PLONK proof.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct PlonkBn254Proof {
    pub public_inputs: [String; 2],
    pub encoded_proof: String,
    pub raw_proof: String,
    pub plonk_vkey_hash: [u8; 32],
}

/// A zero-knowledge proof generated by the Groth16 protocol with a Base64 encoded gnark Groth16
/// proof.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Groth16Bn254Proof {
    pub public_inputs: [String; 2],
    pub encoded_proof: String,
    pub raw_proof: String,
    pub groth16_vkey_hash: [u8; 32],
}

/// The information necessary to verify a proof for a given MIPS program.
#[derive(Clone, Serialize, Deserialize)]
pub struct ZKMVerifyingKey {
    pub vk: MachineVerifyingKey<ZkmGlobalContext>,
}

pub trait HashableKey {
    /// Hash the key into a digest of KoalaBear elements.
    fn hash_koalabear(&self) -> [KoalaBear; DIGEST_SIZE];
}

impl HashableKey for MachineVerifyingKey<ZkmGlobalContext> {
    fn hash_koalabear(&self) -> [KoalaBear; DIGEST_SIZE] {
        let mut inputs = Vec::with_capacity(DIGEST_SIZE + 1 + 14);
        inputs.extend(self.preprocessed_commit);
        inputs.push(self.pc_start);
        inputs.extend(self.initial_global_cumulative_sum.0.x.0);
        inputs.extend(self.initial_global_cumulative_sum.0.y.0);

        poseidon2_hash(inputs)
    }
}
