//! BN254 scalar-field configuration for the outer (BN254-based) proving layer.
//!
//! The field arithmetic and Poseidon2 permutation come from [Plonky3]'s `p3-bn254-fr`
//! crate. The Poseidon2 round constants (width 3) were originally generated by Horizen
//! Labs and are copied verbatim from the `zkhash` reference implementation (authored
//! by Markus Schofnegger and Roman Walch). See [`poseidon2_rc`] for the values and
//! provenance details.
//!
//! [Plonky3]: https://github.com/Plonky3/Plonky3

#![allow(clippy::disallowed_types)]
use std::marker::PhantomData;

pub use p3_bn254_fr::*;
use serde::{Deserialize, Serialize};
use slop_algebra::{ExtensionField, PrimeField32};
use slop_challenger::{IopCtx, MultiField32Challenger};
use slop_poseidon2::ExternalLayerConstants;
use slop_symmetric::{CryptographicHasher, Hash, MultiField32PaddingFreeSponge, PseudoCompressionFunction, TruncatedPermutation};

mod poseidon2_rc;

use poseidon2_rc::{bn254_from_be_hex, RC3_HEX};

pub const OUTER_CHALLENGER_STATE_WIDTH: usize = 3;
pub const OUTER_DIGEST_SIZE: usize = 1;
pub const OUTER_CHALLENGER_RATE: usize = 2;

#[derive(Debug, Clone, Default, Copy, Serialize, Deserialize, Hash, PartialEq, Eq)]
pub struct Poseidon2Bn254GlobalConfig<F, EF>(PhantomData<(F, EF)>);

pub type OuterPerm = Poseidon2Bn254<OUTER_CHALLENGER_STATE_WIDTH>;

pub fn outer_perm() -> OuterPerm {
    const ROUNDS_F: usize = 8;
    const ROUNDS_P: usize = 56;
    let mut round_constants = bn254_poseidon2_rc3();
    let internal_start = ROUNDS_F / 2;
    let internal_end = (ROUNDS_F / 2) + ROUNDS_P;
    let internal_round_constants =
        round_constants.drain(internal_start..internal_end).map(|vec| vec[0]).collect::<Vec<_>>();
    let external_round_constants = ExternalLayerConstants::new(
        round_constants[..ROUNDS_F / 2].to_vec(),
        round_constants[ROUNDS_F / 2..].to_vec(),
    );
    OuterPerm::new(external_round_constants, internal_round_constants)
}

pub fn bn254_poseidon2_rc3() -> Vec<[Bn254Fr; 3]> {
    RC3_HEX
        .iter()
        .map(|row| {
            [bn254_from_be_hex(row[0]), bn254_from_be_hex(row[1]), bn254_from_be_hex(row[2])]
        })
        .collect()
}

/// Wraps a bare-array [`CryptographicHasher`]/[`PseudoCompressionFunction`] to produce a
/// [`Hash`]-wrapped digest, since [`MultiField32Challenger`] can only observe digests in that
/// form (it has no `CanObserve<[Bn254Fr; N]>` impl for the inner permutation field).
#[derive(Clone)]
pub struct HashWrapped<Inner>(Inner);

impl<F, PF, Inner, const N: usize> CryptographicHasher<F, Hash<F, PF, N>> for HashWrapped<Inner>
where
    F: Clone,
    PF: Clone,
    Inner: CryptographicHasher<F, [PF; N]>,
{
    fn hash_iter<I>(&self, input: I) -> Hash<F, PF, N>
    where
        I: IntoIterator<Item = F>,
    {
        Hash::from(self.0.hash_iter(input))
    }
}

impl<F, PF, Inner, const N: usize> PseudoCompressionFunction<Hash<F, PF, N>, 2> for HashWrapped<Inner>
where
    F: Clone,
    PF: Clone,
    Inner: PseudoCompressionFunction<[PF; N], 2>,
{
    fn compress(&self, input: [Hash<F, PF, N>; 2]) -> Hash<F, PF, N> {
        Hash::from(self.0.compress(input.map(|h| h.into())))
    }
}

// `FieldMerkleTreeProver`'s `ComputeTcsOpenings`/`TensorCsProver` impls (in
// `slop_merkle_tree::p3sync`) need the bare-array `CryptographicHasher`/`PseudoCompressionFunction`
// forms in addition to the `Hash`-wrapped ones above (used by `MerkleTreeTcs`/
// `MultiField32Challenger`), so forward straight through to the inner hasher/compressor, which
// already implements them.
impl<F: Clone, PF, Inner, const N: usize> CryptographicHasher<F, [PF; N]> for HashWrapped<Inner>
where
    Inner: CryptographicHasher<F, [PF; N]>,
{
    fn hash_iter<I>(&self, input: I) -> [PF; N]
    where
        I: IntoIterator<Item = F>,
    {
        self.0.hash_iter(input)
    }
}

impl<PF, Inner, const N: usize> PseudoCompressionFunction<[PF; N], 2> for HashWrapped<Inner>
where
    Inner: PseudoCompressionFunction<[PF; N], 2>,
{
    fn compress(&self, input: [[PF; N]; 2]) -> [PF; N] {
        self.0.compress(input)
    }
}

impl<F: PrimeField32, EF: ExtensionField<F>> IopCtx for Poseidon2Bn254GlobalConfig<F, EF> {
    type F = F;

    type EF = EF;

    type Digest = Hash<F, Bn254Fr, OUTER_DIGEST_SIZE>;

    type Challenger = MultiField32Challenger<
        F,
        Bn254Fr,
        OuterPerm,
        OUTER_CHALLENGER_STATE_WIDTH,
        OUTER_CHALLENGER_RATE,
    >;

    type Hasher = HashWrapped<
        MultiField32PaddingFreeSponge<
            F,
            Bn254Fr,
            OuterPerm,
            OUTER_CHALLENGER_STATE_WIDTH,
            16,
            OUTER_DIGEST_SIZE,
        >,
    >;

    type Compressor =
        HashWrapped<TruncatedPermutation<OuterPerm, 2, OUTER_DIGEST_SIZE, OUTER_CHALLENGER_STATE_WIDTH>>;

    fn default_hasher_and_compressor() -> (Self::Hasher, Self::Compressor) {
        let perm = outer_perm();
        let hasher = HashWrapped(
            MultiField32PaddingFreeSponge::<
                F,
                Bn254Fr,
                OuterPerm,
                OUTER_CHALLENGER_STATE_WIDTH,
                16,
                OUTER_DIGEST_SIZE,
            >::new(perm.clone())
            .unwrap(),
        );
        let compressor = HashWrapped(TruncatedPermutation::new(perm.clone()));
        (hasher, compressor)
    }

    fn default_challenger() -> Self::Challenger {
        let default_perm = outer_perm();
        MultiField32Challenger::<
            F,
            Bn254Fr,
            OuterPerm,
            OUTER_CHALLENGER_STATE_WIDTH,
            OUTER_CHALLENGER_RATE,
        >::new(default_perm)
        .unwrap()
    }
}

pub type BNGC<F, EF> = Poseidon2Bn254GlobalConfig<F, EF>;
