[package]
name = "aggregation-host"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
zkm-sdk = { workspace = true }
tracing = { workspace = true }
tokio = { version = "1.21", default-features = false, features = [
    "rt",
    "rt-multi-thread",
] }

[build-dependencies]
zkm-build = { workspace = true }
