use std::{fmt::Debug, fs::File, path::Path};

use anyhow::Result;
use serde::{Deserialize, Serialize};
use strum_macros::{EnumDiscriminants, EnumTryAs};
use zkm_hypercube::ShardProof;
use zkm_primitives::io::ZKMPublicValues;

use zkm_prover::{
    verify::ZKMVerificationError, CorePcsProof, DvSnarkBn254Proof, Groth16Bn254Proof, CoreSC,
    PlonkBn254Proof, ZKMReduceProofWrapper,
};

/// A proof generated with Ziren of a particular proof mode.
/// Consistent with the definition in file crates/verifier/src/stark/mod.rs
#[derive(Clone, Serialize, Deserialize, EnumDiscriminants, EnumTryAs)]
#[strum_discriminants(derive(Default, Hash, PartialOrd, Ord))]
#[strum_discriminants(name(ZKMProofKind))]
pub enum ZKMProof {
    /// A proof generated by the core proof mode.
    ///
    /// The proof size scales linearly with the number of cycles.
    #[strum_discriminants(default)]
    Core(Vec<ShardProof<CoreSC, CorePcsProof>>),
    /// A proof generated by the compress proof mode.
    ///
    /// The proof size is constant, regardless of the number of cycles.
    Compressed(Box<ZKMReduceProofWrapper>),
    /// A proof generated by the Plonk proof mode.
    Plonk(PlonkBn254Proof),
    /// A proof generated by the Groth16 proof mode.
    Groth16(Groth16Bn254Proof),
    /// A proof generated by the DV-SNARK proof mode.
    DvSnark(DvSnarkBn254Proof),
    /// Compressed-proof-to-Groth16 conversion.
    CompressToGroth16,
}

impl Debug for ZKMProof {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ZKMProof::Core(shards) => f.debug_tuple("Core").field(&shards.len()).finish(),
            ZKMProof::Compressed(proof) => f.debug_tuple("Compressed").field(proof).finish(),
            ZKMProof::Plonk(proof) => f.debug_tuple("Plonk").field(proof).finish(),
            ZKMProof::Groth16(proof) => f.debug_tuple("Groth16").field(proof).finish(),
            ZKMProof::DvSnark(proof) => f.debug_tuple("DvSnark").field(proof).finish(),
            ZKMProof::CompressToGroth16 => write!(f, "CompressToGroth16"),
        }
    }
}

/// A proof generated with ZKM, bundled together with stdin, public values, and the Ziren version.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ZKMProofWithPublicValues {
    pub proof: ZKMProof,
    pub public_values: ZKMPublicValues,
    pub zkm_version: String,
}

impl ZKMProofWithPublicValues {
    /// Saves the proof to a path.
    pub fn save(&self, path: impl AsRef<Path>) -> Result<()> {
        bincode::serialize_into(File::create(path).expect("failed to open file"), self)
            .map_err(Into::into)
    }

    /// Loads a proof from a path.
    pub fn load(path: impl AsRef<Path>) -> Result<Self> {
        bincode::deserialize_from(File::open(path).expect("failed to open file"))
            .map_err(Into::into)
    }

    /// Returns the raw proof as a string.
    pub fn raw(&self) -> String {
        match &self.proof {
            ZKMProof::Plonk(plonk) => plonk.raw_proof.clone(),
            ZKMProof::Groth16(groth16) => groth16.raw_proof.clone(),
            _ => unimplemented!(),
        }
    }

    /// Returns the proof encoded as bytes.
    ///
    /// Encoding depends on the proof variant:
    /// - For [`ZKMProof::Compressed`], returns a `bincode` serialization of the [`ZKMProof`] enum.
    ///   This format is used for off-chain STARK verification (e.g. `zkm_verifier::StarkVerifier`).
    /// - For [`ZKMProof::Plonk`] and [`ZKMProof::Groth16`], returns an onchain-friendly encoding:
    ///   the first 4 bytes of the corresponding verifier/vkey hash followed by the decoded proof
    ///   bytes.
    pub fn bytes(&self) -> Vec<u8> {
        match &self.proof {
            ZKMProof::Compressed(_) => {
                bincode::serialize(&self.proof).expect("Invalid stark proof")
            }
            ZKMProof::Plonk(plonk_proof) => {
                if plonk_proof.encoded_proof.is_empty() {
                    // If the proof is empty, then this is a mock proof. The mock Ziren verifier
                    // expects an empty byte array for verification, so return an empty byte array.
                    return Vec::new();
                }

                let proof_bytes =
                    hex::decode(&plonk_proof.encoded_proof).expect("Invalid Plonk proof");
                [plonk_proof.plonk_vkey_hash[..4].to_vec(), proof_bytes].concat()
            }
            ZKMProof::Groth16(groth16_proof) => {
                if groth16_proof.encoded_proof.is_empty() {
                    // If the proof is empty, then this is a mock proof. The mock Ziren verifier
                    // expects an empty byte array for verification, so return an empty byte array.
                    return Vec::new();
                }

                let proof_bytes =
                    hex::decode(&groth16_proof.encoded_proof).expect("Invalid Groth16 proof");
                [groth16_proof.groth16_vkey_hash[..4].to_vec(), proof_bytes].concat()
            }
            _ => unimplemented!(
                "only Compressed (STARK), Plonk and Groth16 proofs are supported by bytes()"
            ),
        }
    }
}

pub type ZKMCoreProofVerificationError = ZKMVerificationError;

pub type ZKMCompressedProofVerificationError = ZKMVerificationError;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_plonk_proof_bytes() {
        let plonk_proof = ZKMProofWithPublicValues {
            proof: ZKMProof::Plonk(PlonkBn254Proof {
                encoded_proof: "ab".to_string(),
                plonk_vkey_hash: [0; 32],
                public_inputs: ["".to_string(), "".to_string()],
                raw_proof: "".to_string(),
            }),
            public_values: ZKMPublicValues::new(),
            zkm_version: "".to_string(),
        };
        let expected_bytes = [vec![0, 0, 0, 0], hex::decode("ab").unwrap()].concat();
        assert_eq!(plonk_proof.bytes(), expected_bytes);
    }

    #[test]
    fn test_groth16_proof_bytes() {
        let groth16_proof = ZKMProofWithPublicValues {
            proof: ZKMProof::Groth16(Groth16Bn254Proof {
                encoded_proof: "ab".to_string(),
                groth16_vkey_hash: [0; 32],
                public_inputs: ["".to_string(), "".to_string()],
                raw_proof: "".to_string(),
            }),
            public_values: ZKMPublicValues::new(),
            zkm_version: "".to_string(),
        };
        let expected_bytes = [vec![0, 0, 0, 0], hex::decode("ab").unwrap()].concat();
        assert_eq!(groth16_proof.bytes(), expected_bytes);
    }

    #[test]
    fn test_mock_plonk_proof_bytes() {
        let mock_plonk_proof = ZKMProofWithPublicValues {
            proof: ZKMProof::Plonk(PlonkBn254Proof {
                encoded_proof: "".to_string(),
                plonk_vkey_hash: [0; 32],
                public_inputs: ["".to_string(), "".to_string()],
                raw_proof: "".to_string(),
            }),
            public_values: ZKMPublicValues::new(),
            zkm_version: "".to_string(),
        };
        assert_eq!(mock_plonk_proof.bytes(), Vec::<u8>::new());
    }

    #[test]
    fn test_mock_groth16_proof_bytes() {
        let mock_groth16_proof = ZKMProofWithPublicValues {
            proof: ZKMProof::Groth16(Groth16Bn254Proof {
                encoded_proof: "".to_string(),
                groth16_vkey_hash: [0; 32],
                public_inputs: ["".to_string(), "".to_string()],
                raw_proof: "".to_string(),
            }),
            public_values: ZKMPublicValues::new(),
            zkm_version: "".to_string(),
        };
        assert_eq!(mock_groth16_proof.bytes(), Vec::<u8>::new());
    }

    #[test]
    #[should_panic(
        expected = "only Compressed (STARK), Plonk and Groth16 proofs are supported by bytes()"
    )]
    fn test_core_proof_bytes_unimplemented() {
        let core_proof = ZKMProofWithPublicValues {
            proof: ZKMProof::Core(vec![]),
            public_values: ZKMPublicValues::new(),
            zkm_version: "".to_string(),
        };
        core_proof.bytes();
    }
}
