use permutation::Poseidon2Degree3Cols;
use zkm_derive::AlignedBorrow;

pub mod air;
pub mod permutation;
pub mod trace;

/// The width of the permutation.
pub const WIDTH: usize = 16;

/// The rate of the permutation.
pub const RATE: usize = WIDTH / 2;

/// The number of external rounds.
pub const NUM_EXTERNAL_ROUNDS: usize = 8;

/// The number of internal rounds.
///
/// Must match `poseidon2_init()` in zkm-primitives (KoalaBear/α=3 reference R_P = 20), since the
/// Poseidon2Permute precompile witness is generated by that permutation.
pub const NUM_INTERNAL_ROUNDS: usize = 20;

/// The total number of rounds.
pub const NUM_ROUNDS: usize = NUM_EXTERNAL_ROUNDS + NUM_INTERNAL_ROUNDS;

/// The number of columns in the Poseidon2 operation.
pub const NUM_POSEIDON2_OPERATION_COLUMNS: usize = std::mem::size_of::<Poseidon2Operation<u8>>();

/// A set of columns needed to compute the Poseidon2 operation.
#[derive(AlignedBorrow, Debug, Clone, Copy)]
#[repr(C)]
pub struct Poseidon2Operation<T: Copy> {
    /// The permutation.
    pub permutation: Poseidon2Degree3Cols<T>,
}
