extern crate alloc;

use core::borrow::Borrow;
use itertools::Itertools;

use p3_field::PrimeField32;
use zkm_hypercube::{air::PublicValues, word::Word};
use zkm_primitives::io::ZKMPublicValues;

use crate::proof::{ZKMProof, ZKMVerifyingKey};
use error::CompressedError;
use verify::verify_compressed_proof;

pub mod error;
mod verify;

/// A verifier for compressed (recursively reduced) zero-knowledge proofs.
#[derive(Debug)]
pub struct CompressedVerifier;

impl CompressedVerifier {
    /// Verifies a Ziren compressed proof, as generated by the Ziren SDK.
    ///
    /// # Arguments
    ///
    /// * `proof` - The proof bytes.
    /// * `public_inputs` - The Ziren public inputs, which are committed by the guest as a bincode-serialized byte array.
    /// * `zkm_vk` - The Ziren vkey bytes.
    ///   This is generated in the following manner:
    ///
    /// ```ignore
    /// use zkm_sdk::ProverClient;
    /// let client = ProverClient::new();
    /// let (pk, vk) = client.setup(ELF);
    /// ```
    ///
    /// # Returns
    ///
    /// A success [`Result`] if verification succeeds, or a [`CompressedError`] if verification fails.
    ///
    /// Compared to `verify_proof()`, it performs a consistency check between
    /// user-supplied public values and those committed in the proof.
    pub fn verify(
        proof: &[u8],
        zkm_public_inputs: &[u8],
        zkm_vk: &[u8],
    ) -> Result<(), CompressedError> {
        let proof: ZKMProof = bincode::deserialize(proof).expect("failed to deserialize the proof");
        let ZKMProof::Compressed(proof) = proof else { panic!("expected a compressed proof") };
        let public_inputs = ZKMPublicValues::from(zkm_public_inputs);
        let vk: ZKMVerifyingKey =
            bincode::deserialize(zkm_vk).expect("failed to deserialize the vk");

        let proof_public_values: &PublicValues<Word<_>, _> =
            proof.proof.public_values.as_slice().borrow();

        // Get the committed value digest bytes.
        let committed_value_digest_bytes = proof_public_values
            .committed_value_digest
            .iter()
            .flat_map(|w| w.0.iter().map(|x| x.as_canonical_u32() as u8))
            .collect_vec();

        // Make sure the committed value digest matches the public values hash.
        for (a, b) in committed_value_digest_bytes.iter().zip_eq(public_inputs.hash()) {
            if *a != b {
                return Err(CompressedError::InvalidPublicValues);
            }
        }

        verify_compressed_proof(&vk, &proof)
    }

    /// Verifies a Ziren compressed proof, as generated by the Ziren SDK.
    ///
    /// # Arguments
    ///
    /// * `proof` - The proof bytes.
    /// * `zkm_vk` - The Ziren vkey bytes.
    ///
    /// Compared to `verify()`, it does not perform a consistency check between
    /// user-supplied public values and those committed in the proof.
    pub fn verify_proof(proof: &[u8], zkm_vk: &[u8]) -> Result<(), CompressedError> {
        let proof: ZKMProof = bincode::deserialize(proof).expect("failed to deserialize the proof");
        let ZKMProof::Compressed(proof) = proof else { panic!("expected a compressed proof") };
        let vk: ZKMVerifyingKey =
            bincode::deserialize(zkm_vk).expect("failed to deserialize the vk");

        verify_compressed_proof(&vk, &proof)
    }
}
